version: '3.8'

services:
  app:
    build: .
    container_name: node_rest_api
    ports:
      - "8080:8080"  # Наш единый защищенный HTTPS REST API
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongodb:27017/storagedb
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - BUCKET_NAME=images
      - USERS=users
      - JWT_SECRET=your_super_secret_jwt_key_123
      - JWT_EXPIRES_IN=4h
      - S3_REF_EXPIRES=3600
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongodb
      - minio

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"    # API MinIO
      - "9001:9001"    # Консоль управления (Браузер)
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"

volumes:
  mongo_data:
  minio_data:
